name: BedwarsItemShop
version: '${project.version}'
main: me.ram.bedwarsitemshop.Main
authors:
  - Ram
  - YukiEnd
depend: [ BedwarsRel ]
softdepend: [ BedwarsXP, BedwarsScoreBoardAddon ]

commands:
  bedwarsitemshop:
    aliases: [ bwis ]

permissions:
  bedwarsitemshop.reload:
    default: op

