name: BedwarsItemShop
version: '${project.version}'
main: me.ram.bedwarsitemshop.Main
authors:
  - Ram
  - YukiEnd
depends: [ BedwarsRel ]
softdepends: [ BedwarsXP ]

commands:
  bedwarsitemshop:
    aliases: [ bwis ]

permissions:
  bedwarsitemshop.reload:
    default: op

